### Calcular folhas
GET http://localhost:3000/folha/calcular

### Listar folhas
GET http://localhost:3000/folha/listar

### Cadastrar folhas
POST http://localhost:3000/folha/cadastrar
Content-Type: application/json

{
   "mes" : 5,
   "ano" : 2022,
   "horas" : 1500,
   "valor": 50,
   "nome": "Aramis",  
   "cpf": "123.456.789-10"
}